<a href="https://colab.research.google.com/github/yunesmchaar/web_Scraping/blob/main/Scrapping.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install requests

Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests) (2026.1.4)

In [2]:
import requests

In [3]:
url = "https://www.scrapethissite.com/pages/simple/"
page = requests.get(url)

In [4]:
source = page.text
print(source)

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Countries of the World: A Simple Example | Scrape This Site | A public sandbox for learning web scraping</title>
    <link rel="icon" type="image/png" href="/static/images/scraper-icon.png" />

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="A single page that lists information about all the countries in the world. Good for those just get started with web scraping.">

    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">
    <link href='https://fonts.googleapis.com/css?family=Lato:400,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="/static/css/styles.css">


<meta name="robots" content="noindex">
<link href="https://lipis.github.io/flag-icon-css/css/flag-icon.css" rel="stylesheet">


  </head>

  <body>
    <nav id="site-nav">
            <div class="container">
                <div class="col-md-12">
                    <ul class="nav nav-tabs">
                        <li id="nav-homepage">
                            <a href="/" class="nav-link hidden-sm hidden-xs">
                                <img src="/static/images/scraper-icon.png" id="nav-logo">
                                Scrape This Site
                            </a>
                        </li>
                        <li id="nav-sandbox">
                            <a href="/pages/" class="nav-link">
                                <i class="glyphicon glyphicon-console hidden-sm hidden-xs"></i>
                                Sandbox
                            </a>
                        </li>
                        <li id="nav-lessons">
                            <a href="/lessons/" class="nav-link">
                                <i class="glyphicon glyphicon-education hidden-sm hidden-xs"></i>
                                Lessons
                            </a>
                        </li>
                        <li id="nav-faq">
                            <a href="/faq/" class="nav-link">
                                <i class="glyphicon glyphicon-flag hidden-sm hidden-xs"></i>
                                FAQ
                            </a>
                        </li>

                        <li id="nav-login" class="pull-right">
                            <a href="/login/" class="nav-link">
                                Login
                            </a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>

        <script type="text/javascript">
            var path = document.location.pathname;
            var tab = undefined;
            if (path === "/"){
                tab = document.querySelector("#nav-homepage");
            } else if (path.indexOf("/faq/") === 0){
                tab = document.querySelector("#nav-faq");
            } else if (path.indexOf("/lessons/") === 0){
                tab = document.querySelector("#nav-lessons");
            } else if (path.indexOf("/pages/") === 0) {
                tab = document.querySelector("#nav-sandbox");
            } else if (path.indexOf("/login/") === 0) {
                tab = document.querySelector("#nav-login");
            }
            tab.classList.add("active")
        </script>



    <div id="page">

        <section id="countries">
            <div class="container">

                <div class="row">
                    <div class="col-md-12">
                        <h1>
                            Countries of the World: A Simple Example
                            <small>250 items</small>
                        </h1>
                        <hr />
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <p class="lead">
                            A single page that lists information about all the countries in the world. Good for those just get started with web scraping.
                            Practice looking for patterns in the HTML that will allow you to extract information about each country. Then, build a simple web scraper that makes a request to this page, parses the HTML and prints out each country&#39;s name.
                        </p>
                        <hr />
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <p>
                            <i class="glyphicon glyphicon-education"></i> There are <a href="/lessons/">4 video lessons</a> that show you how to scrape this page.
                        </p>
                        <hr />
                    </div>
                    <div class="col-md-6 text-right">
                        <p>

                                Data via
                                <a href="http://peric.github.io/GetCountries/" class="data-attribution" target="_blank">http://peric.github.io/GetCountries/</a>

                        </p>
                        <hr />
                    </div>
                </div>

                <div class="row">

                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-ad"></i>
                            Andorra
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Andorra la Vella</span><br>
                            <strong>Population:</strong> <span class="country-population">84000</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">468.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-ae"></i>
                            United Arab Emirates
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Abu Dhabi</span><br>
                            <strong>Population:</strong> <span class="country-population">4975593</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">82880.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-af"></i>
                            Afghanistan
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Kabul</span><br>
                            <strong>Population:</strong> <span class="country-population">29121286</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">647500.0</span><br>
                        </div>
                    </div><!--.col-->

                </div><!--.row-->
                <div class="row">



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-ag"></i>
                            Antigua and Barbuda
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">St. John&#39;s</span><br>
                            <strong>Population:</strong> <span class="country-population">86754</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">443.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-ai"></i>
                            Anguilla
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">The Valley</span><br>
                            <strong>Population:</strong> <span class="country-population">13254</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">102.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-al"></i>
                            Albania
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Tirana</span><br>
                            <strong>Population:</strong> <span class="country-population">2986952</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">28748.0</span><br>
                        </div>
                    </div><!--.col-->

                </div><!--.row-->
                <div class="row">



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-am"></i>
                            Armenia
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Yerevan</span><br>
                            <strong>Population:</strong> <span class="country-population">2968000</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">29800.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-ao"></i>
                            Angola
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Luanda</span><br>
                            <strong>Population:</strong> <span class="country-population">13068161</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1246700.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-aq"></i>
                            Antarctica
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">None</span><br>
                            <strong>Population:</strong> <span class="country-population">0</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1.4E7</span><br>
                        </div>
                    </div><!--.col-->

                </div><!--.row-->
                <div class="row">



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-ar"></i>
                            Argentina
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Buenos Aires</span><br>
                            <strong>Population:</strong> <span class="country-population">41343201</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">2766890.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-as"></i>
                            American Samoa
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Pago Pago</span><br>
                            <strong>Population:</strong> <span class="country-population">57881</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">199.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-at"></i>
                            Austria
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Vienna</span><br>
                            <strong>Population:</strong> <span class="country-population">8205000</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">83858.0</span><br>
                        </div>
                    </div><!--.col-->

                </div><!--.row-->
                <div class="row">



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-au"></i>
                            Australia
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Canberra</span><br>
                            <strong>Population:</strong> <span class="country-population">21515754</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">7686850.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-aw"></i>
                            Aruba
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Oranjestad</span><br>
                            <strong>Population:</strong> <span class="country-population">71566</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">193.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-ax"></i>
                            Åland
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Mariehamn</span><br>
                            <strong>Population:</strong> <span class="country-population">26711</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1580.0</span><br>
                        </div>
                    </div><!--.col-->

                </div><!--.row-->
                <div class="row">



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-az"></i>
                            Azerbaijan
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Baku</span><br>
                            <strong>Population:</strong> <span class="country-population">8303512</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">86600.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-ba"></i>
                            Bosnia and Herzegovina
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Sarajevo</span><br>
                            <strong>Population:</strong> <span class="country-population">4590000</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">51129.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-bb"></i>
                            Barbados
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Bridgetown</span><br>
                            <strong>Population:</strong> <span class="country-population">285653</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">431.0</span><br>
                        </div>
                    </div><!--.col-->

                </div><!--.row-->
                <div class="row">



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-bd"></i>
                            Bangladesh
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Dhaka</span><br>
                            <strong>Population:</strong> <span class="country-population">156118464</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">144000.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-be"></i>
                            Belgium
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Brussels</span><br>
                            <strong>Population:</strong> <span class="country-population">10403000</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">30510.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-bf"></i>
                            Burkina Faso
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Ouagadougou</span><br>

In [5]:
print(page.content)

b'<!doctype html>\n<html lang="en">\n  <head>\n    <meta charset="utf-8">\n    <title>Countries of the World: A Simple Example | Scrape This Site | A public sandbox for learning web scraping</title>\n    <link rel="icon" type="image/png" href="/static/images/scraper-icon.png" />\n\n    <meta name="viewport" content="width=device-width, initial-scale=1.0">\n    <meta name="description" content="A single page that lists information about all the countries in the world. Good for those just get started with web scraping.">\n\n    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">\n    <link href=\'https://fonts.googleapis.com/css?family=Lato:400,700\' rel=\'stylesheet\' type=\'text/css\'>\n    <link rel="stylesheet" type="text/css" href="/static/css/styles.css">\n\n    \n<meta name="robots" content="noindex">\n<link href="https://lipis.github.io/flag-icon-css/css/flag-icon.css" rel="stylesheet">\n\n\n  </head>\n\n  <body>\n    <nav id="site-nav">\n            <div class="container">\n                <div class="col-md-12">\n                    <ul class="nav nav-tabs">\n                        <li id="nav-homepage">\n                            <a href="/" class="nav-link hidden-sm hidden-xs">\n                                <img src="/static/images/scraper-icon.png" id="nav-logo">\n                                Scrape This Site\n                            </a>\n                        </li>\n                        <li id="nav-sandbox">\n                            <a href="/pages/" class="nav-link">\n                                <i class="glyphicon glyphicon-console hidden-sm hidden-xs"></i>\n                                Sandbox\n                            </a>\n                        </li>\n                        <li id="nav-lessons">\n                            <a href="/lessons/" class="nav-link">\n                                <i class="glyphicon glyphicon-education hidden-sm hidden-xs"></i>\n                                Lessons\n                            </a>\n                        </li>\n                        <li id="nav-faq">\n                            <a href="/faq/" class="nav-link">\n                                <i class="glyphicon glyphicon-flag hidden-sm hidden-xs"></i>\n                                FAQ\n                            </a>\n                        </li>\n                        \n                        <li id="nav-login" class="pull-right">\n                            <a href="/login/" class="nav-link">\n                                Login\n                            </a>\n                        </li>\n                        \n                    </ul>\n                </div>\n            </div>\n        </nav>\n\n        <script type="text/javascript">\n            var path = document.location.pathname;\n            var tab = undefined;\n            if (path === "/"){\n                tab = document.querySelector("#nav-homepage");\n            } else if (path.indexOf("/faq/") === 0){\n                tab = document.querySelector("#nav-faq");\n            } else if (path.indexOf("/lessons/") === 0){\n                tab = document.querySelector("#nav-lessons");\n            } else if (path.indexOf("/pages/") === 0) {\n                tab = document.querySelector("#nav-sandbox");\n            } else if (path.indexOf("/login/") === 0) {\n                tab = document.querySelector("#nav-login");\n            }\n            tab.classList.add("active")\n        </script>\n\n    \n\n    <div id="page">\n\n        <section id="countries">\n            <div class="container">\n\n                <div class="row">\n                    <div class="col-md-12">\n                        <h1>\n                            Countries of the World: A Simple Example\n                            <small>250 items</small>\n                        </h1>\n                        <hr />\n                    </div>\n                </div>\n                <div class="row">\n                    <div class="col-md-12">\n                        <p class="lead">\n                            A single page that lists information about all the countries in the world. Good for those just get started with web scraping.\n                            Practice looking for patterns in the HTML that will allow you to extract information about each country. Then, build a simple web scraper that makes a request to this page, parses the HTML and prints out each country&#39;s name.\n                        </p>\n                        <hr />\n                    </div>\n                </div>\n                <div class="row">\n                    <div class="col-md-6">\n                        <p>\n                            <i class="glyphicon glyphicon-education"></i> There are <a href="/lessons/">4 video lessons</a> that show you how to scrape this page.\n                        </p>\n                        <hr />\n                    </div>\n                    <div class="col-md-6 text-right">\n                        <p>\n                            \n                                Data via\n                                <a href="http://peric.github.io/GetCountries/" class="data-attribution" target="_blank">http://peric.github.io/GetCountries/</a>\n                            \n                        </p>\n                        <hr />\n                    </div>\n                </div>\n\n                <div class="row">\n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-ad"></i>\n                            Andorra\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Andorra la Vella</span><br>\n                            <strong>Population:</strong> <span class="country-population">84000</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">468.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-ae"></i>\n                            United Arab Emirates\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Abu Dhabi</span><br>\n                            <strong>Population:</strong> <span class="country-population">4975593</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">82880.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-af"></i>\n                            Afghanistan\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Kabul</span><br>\n                            <strong>Population:</strong> <span class="country-population">29121286</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">647500.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                </div><!--.row-->\n                <div class="row">\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-ag"></i>\n                            Antigua and Barbuda\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">St. John&#39;s</span><br>\n                            <strong>Population:</strong> <span class="country-population">86754</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">443.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-ai"></i>\n                            Anguilla\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">The Valley</span><br>\n                            <strong>Population:</strong> <span class="country-population">13254</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">102.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-al"></i>\n                            Albania\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Tirana</span><br>\n                            <strong>Population:</strong> <span class="country-population">2986952</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">28748.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                </div><!--.row-->\n                <div class="row">\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-am"></i>\n                            Armenia\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Yerevan</span><br>\n                            <strong>Population:</strong> <span class="country-population">2968000</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">29800.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-ao"></i>\n                            Angola\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Luanda</span><br>\n                            <strong>Population:</strong> <span class="country-population">13068161</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1246700.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-aq"></i>\n                            Antarctica\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">None</span><br>\n                            <strong>Population:</strong> <span class="country-population">0</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1.4E7</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                </div><!--.row-->\n                <div class="row">\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-ar"></i>\n                            Argentina\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Buenos Aires</span><br>\n                            <strong>Population:</strong> <span class="country-population">41343201</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">2766890.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-as"></i>\n                            American Samoa\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Pago Pago</span><br>\n                            <strong>Population:</strong> <span class="country-population">57881</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">199.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-at"></i>\n                            Austria\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Vienna</span><br>\n                            <strong>Population:</strong> <span class="country-population">8205000</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">83858.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                </div><!--.row-->\n                <div class="row">\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-au"></i>\n                            Australia\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Canberra</span><br>\n                            <strong>Population:</strong> <span class="country-population">21515754</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">7686850.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-aw"></i>\n                            Aruba\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Oranjestad</span><br>\n                            <strong>Population:</strong> <span class="country-population">71566</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">193.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-ax"></i>\n                            \xc3\x85land\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Mariehamn</span><br>\n                            <strong>Population:</strong> <span class="country-population">26711</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1580.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                </div><!--.row-->\n                <div class="row">\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-az"></i>\n                            Azerbaijan\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Baku</span><br>\n                            <strong>Population:</strong> <span class="country-population">8303512</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">86600.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-ba"></i>\n                            Bosnia and Herzegovina\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Sarajevo</span><br>\n                            <strong>Population:</strong> <span class="country-population">4590000</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">51129.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-bb"></i>\n                            Barbados\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Bridgetown</span><br>\n                            <strong>Population:</strong> <span class="country-population">285653</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">431.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                </div><!--.row-->\n                <div class="row">\n                    \n                    \n                    \n                    <div class="col-

In [6]:
print(type(page.content))
print(type(page.text))

<class 'bytes'>
<class 'str'>

In [8]:
import requests
from bs4 import BeautifulSoup
url = 'https://www.scrapethissite.com/pages/simple/'
#page = requests.get(url)
#page.content
page.encoding = page.apparent_encoding
soup = BeautifulSoup(page.text,'html.parser')
print(soup)

<!DOCTYPE html>

<html lang="en">
<head>
<meta charset="utf-8"/>
<title>Countries of the World: A Simple Example | Scrape This Site | A public sandbox for learning web scraping</title>
<link href="/static/images/scraper-icon.png" rel="icon" type="image/png"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<meta content="A single page that lists information about all the countries in the world. Good for those just get started with web scraping." name="description"/>
<link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" rel="stylesheet"/>
<link href="https://fonts.googleapis.com/css?family=Lato:400,700" rel="stylesheet" type="text/css"/>
<link href="/static/css/styles.css" rel="stylesheet" type="text/css"/>
<meta content="noindex" name="robots"/>
<link href="https://lipis.github.io/flag-icon-css/css/flag-icon.css" rel="stylesheet"/>
</head>
<body>
<nav id="site-nav">
<div class="container">
<div class="col-md-12">
<ul class="nav nav-tabs">
<li id="nav-homepage">
<a class="nav-link hidden-sm hidden-xs" href="/">
<img id="nav-logo" src="/static/images/scraper-icon.png"/>
                                Scrape This Site
                            </a>
</li>
<li id="nav-sandbox">
<a class="nav-link" href="/pages/">
<i class="glyphicon glyphicon-console hidden-sm hidden-xs"></i>
                                Sandbox
                            </a>
</li>
<li id="nav-lessons">
<a class="nav-link" href="/lessons/">
<i class="glyphicon glyphicon-education hidden-sm hidden-xs"></i>
                                Lessons
                            </a>
</li>
<li id="nav-faq">
<a class="nav-link" href="/faq/">
<i class="glyphicon glyphicon-flag hidden-sm hidden-xs"></i>
                                FAQ
                            </a>
</li>
<li class="pull-right" id="nav-login">
<a class="nav-link" href="/login/">
                                Login
                            </a>
</li>
</ul>
</div>
</div>
</nav>
<script type="text/javascript">
            var path = document.location.pathname;
            var tab = undefined;
            if (path === "/"){
                tab = document.querySelector("#nav-homepage");
            } else if (path.indexOf("/faq/") === 0){
                tab = document.querySelector("#nav-faq");
            } else if (path.indexOf("/lessons/") === 0){
                tab = document.querySelector("#nav-lessons");
            } else if (path.indexOf("/pages/") === 0) {
                tab = document.querySelector("#nav-sandbox");
            } else if (path.indexOf("/login/") === 0) {
                tab = document.querySelector("#nav-login");
            }
            tab.classList.add("active")
        </script>
<div id="page">
<section id="countries">
<div class="container">
<div class="row">
<div class="col-md-12">
<h1>
                            Countries of the World: A Simple Example
                            <small>250 items</small>
</h1>
<hr/>
</div>
</div>
<div class="row">
<div class="col-md-12">
<p class="lead">
                            A single page that lists information about all the countries in the world. Good for those just get started with web scraping.
                            Practice looking for patterns in the HTML that will allow you to extract information about each country. Then, build a simple web scraper that makes a request to this page, parses the HTML and prints out each country's name.
                        </p>
<hr/>
</div>
</div>
<div class="row">
<div class="col-md-6">
<p>
<i class="glyphicon glyphicon-education"></i> There are <a href="/lessons/">4 video lessons</a> that show you how to scrape this page.
                        </p>
<hr/>
</div>
<div class="col-md-6 text-right">
<p>

                                Data via
                                <a class="data-attribution" href="http://peric.github.io/GetCountries/" target="_blank">http://peric.github.io/GetCountries/</a>
</p>
<hr/>
</div>
</div>
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ad"></i>
                            Andorra
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Andorra la Vella</span><br/>
<strong>Population:</strong> <span class="country-population">84000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">468.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ae"></i>
                            United Arab Emirates
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Abu Dhabi</span><br/>
<strong>Population:</strong> <span class="country-population">4975593</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">82880.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-af"></i>
                            Afghanistan
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Kabul</span><br/>
<strong>Population:</strong> <span class="country-population">29121286</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">647500.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ag"></i>
                            Antigua and Barbuda
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">St. John's</span><br/>
<strong>Population:</strong> <span class="country-population">86754</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">443.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ai"></i>
                            Anguilla
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">The Valley</span><br/>
<strong>Population:</strong> <span class="country-population">13254</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">102.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-al"></i>
                            Albania
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Tirana</span><br/>
<strong>Population:</strong> <span class="country-population">2986952</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">28748.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-am"></i>
                            Armenia
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Yerevan</span><br/>
<strong>Population:</strong> <span class="country-population">2968000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">29800.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ao"></i>
                            Angola
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Luanda</span><br/>
<strong>Population:</strong> <span class="country-population">13068161</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1246700.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-aq"></i>
                            Antarctica
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">None</span><br/>
<strong>Population:</strong> <span class="country-population">0</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1.4E7</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ar"></i>
                            Argentina
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Buenos Aires</span><br/>
<strong>Population:</strong> <span class="country-population">41343201</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">2766890.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-as"></i>
                            American Samoa
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Pago Pago</span><br/>
<strong>Population:</strong> <span class="country-population">57881</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">199.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-at"></i>
                            Austria
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Vienna</span><br/>
<strong>Population:</strong> <span class="country-population">8205000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">83858.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-au"></i>
                            Australia
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Canberra</span><br/>
<strong>Population:</strong> <span class="country-population">21515754</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">7686850.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-aw"></i>
                            Aruba
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Oranjestad</span><br/>
<strong>Population:</strong> <span class="country-population">71566</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">193.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ax"></i>
                            Åland
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Mariehamn</span><br/>
<strong>Population:</strong> <span class="country-population">26711</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1580.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-az"></i>
                            Azerbaijan
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Baku</span><br/>
<strong>Population:</strong> <span class="country-population">8303512</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">86600.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ba"></i>
                            Bosnia and Herzegovina
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Sarajevo</span><br/>
<strong>Population:</strong> <span class="country-population">4590000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">51129.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bb"></i>
                            Barbados
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Bridgetown</span><br/>
<strong>Population:</strong> <span class="country-population">285653</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">431.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bd"></i>
                            Bangladesh
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Dhaka</span><br/>
<strong>Population:</strong> <span class="country-population">156118464</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">144000.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-be"></i>
                            Belgium
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Brussels</span><br/>
<strong>Population:</strong> <span class="country-population">10403000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">30510.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bf"></i>
                            Burkina Faso
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Ouagadougou</span><br/>
<strong>Population:</strong> <span class="country-population">16241811</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">274200.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bg"></i>
                            Bulgaria
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Sofia</span><br/>
<strong>Population:</strong> <span class="country-population">7148785</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">110910.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bh"></i>
                            Bahrain
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Manama</span><br/>
<strong>Population:</strong> <span class="country-population">738004</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">665.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bi"></i>
                            Burundi
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Bujumbura</span><br/>
<strong>Population:</strong> <span class="country-population">9863117</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">27830.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bj"></i>
                            Benin
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Porto-Novo</span><br/>
<strong>Population:</strong> <span class="country-population">9056010</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">112620.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bl"></i>
                            Saint Barthélemy
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Gustavia</span><br/>
<strong>Population:</strong> <span class="country-population">8450</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">21.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bm"></i>
                            Bermuda
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Hamilton</span><br/>
<strong>Population:</strong> <span class="country-population">65365</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">53.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bn"></i>
                            Brunei
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Bandar Seri Begawan</span><br/>
<strong>Population:</strong> <span class="country-population">395027</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">5770.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bo"></i>
                            Bolivia
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Sucre</span><br/>
<strong>Population:</strong> <span class="country-population">9947418</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1098580.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bq"></i>
                            Bonaire
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Kralendijk</span><br/>
<strong>Population:</strong> <span class="country-population">18012</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">328.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-br"></i>
                            Brazil
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Brasília</span><br/>
<strong>Population:</strong> <span class="country-population">201103330</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">8511965.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bs"></i>
                            Bahamas
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Nassau</span><br/>
<strong>Population:</strong> <span class="country-population">301790</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">13940.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bt"></i>
                            Bhutan
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Thimphu</span><br/>
<strong>Population:</strong> <span class="country-population">699847</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">47000.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bv"></i>
                            Bouvet Island

In [12]:
print(soup.h1)

<h1>
                            Countries of the World: A Simple Example
                            <small>250 items</small>
</h1>

In [13]:
print(soup.h1.text)

                            Countries of the World: A Simple Example
                            250 items

In [14]:
print(soup.h1.contents)

['\n                            Countries of the World: A Simple Example\n                            ', <small>250 items</small>, '\n']

In [15]:
print(soup.h1.parent.name)

div

In [17]:
print(soup.p.text)

                            A single page that lists information about all the countries in the world. Good for those just get started with web scraping.
                            Practice looking for patterns in the HTML that will allow you to extract information about each country. Then, build a simple web scraper that makes a request to this page, parses the HTML and prints out each country's name.

In [20]:
soup.p.text.strip()

"A single page that lists information about all the countries in the world. Good for those just get started with web scraping.\n                            Practice looking for patterns in the HTML that will allow you to extract information about each country. Then, build a simple web scraper that makes a request to this page, parses the HTML and prints out each country's name."

In [21]:
p=soup.p

In [22]:
p

<p class="lead">
                            A single page that lists information about all the countries in the world. Good for those just get started with web scraping.
                            Practice looking for patterns in the HTML that will allow you to extract information about each country. Then, build a simple web scraper that makes a request to this page, parses the HTML and prints out each country's name.
                        </p>

In [23]:
for parent in p.parents:
  print(parent.name)

div
div
div
section
div
body
html
[document]

In [27]:
p=soup.select('p')
p

[<p class="lead">
                             A single page that lists information about all the countries in the world. Good for those just get started with web scraping.
                             Practice looking for patterns in the HTML that will allow you to extract information about each country. Then, build a simple web scraper that makes a request to this page, parses the HTML and prints out each country's name.
                         </p>,
 <p>
 <i class="glyphicon glyphicon-education"></i> There are <a href="/lessons/">4 video lessons</a> that show you how to scrape this page.
                         </p>,
 <p>

                                 Data via
                                 <a class="data-attribution" href="http://peric.github.io/GetCountries/" target="_blank">http://peric.github.io/GetCountries/</a>
 </p>]

In [28]:
p[0].text.strip()

"A single page that lists information about all the countries in the world. Good for those just get started with web scraping.\n                            Practice looking for patterns in the HTML that will allow you to extract information about each country. Then, build a simple web scraper that makes a request to this page, parses the HTML and prints out each country's name."

In [31]:
import pandas as pd
df = pd.DataFrame(columns = ['Country'])
df

Empty DataFrame
Columns: [Country]
Index: []

In [32]:
country_name = soup.find_all('h3')
country_name

[<h3 class="country-name">
 <i class="flag-icon flag-icon-ad"></i>
                             Andorra
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ae"></i>
                             United Arab Emirates
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-af"></i>
                             Afghanistan
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ag"></i>
                             Antigua and Barbuda
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ai"></i>
                             Anguilla
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-al"></i>
                             Albania
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-am"></i>
                             Armenia
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ao"></i>
                             Angola
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-aq"></i>
                             Antarctica
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ar"></i>
                             Argentina
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-as"></i>
                             American Samoa
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-at"></i>
                             Austria
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-au"></i>
                             Australia
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-aw"></i>
                             Aruba
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ax"></i>
                             Åland
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-az"></i>
                             Azerbaijan
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ba"></i>
                             Bosnia and Herzegovina
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bb"></i>
                             Barbados
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bd"></i>
                             Bangladesh
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-be"></i>
                             Belgium
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bf"></i>
                             Burkina Faso
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bg"></i>
                             Bulgaria
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bh"></i>
                             Bahrain
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bi"></i>
                             Burundi
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bj"></i>
                             Benin
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bl"></i>
                             Saint Barthélemy
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bm"></i>
                             Bermuda
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bn"></i>
                             Brunei
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bo"></i>
                             Bolivia
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bq"></i>
                             Bonaire
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-br"></i>
                             Brazil
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bs"></i>
                             Bahamas
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bt"></i>
                             Bhutan
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bv"></i>
                             Bouvet Island
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bw"></i>
                             Botswana
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-by"></i>
                             Belarus
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bz"></i>
                             Belize
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ca"></i>
                             Canada
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cc"></i>
                             Cocos [Keeling] Islands
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cd"></i>
                             Democratic Republic of the Congo
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cf"></i>
                             Central African Republic
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cg"></i>
                             Republic of the Congo
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ch"></i>
                             Switzerland
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ci"></i>
                             Ivory Coast
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ck"></i>
                             Cook Islands
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cl"></i>
                             Chile
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cm"></i>
                             Cameroon
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cn"></i>
                             China
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-co"></i>
                             Colombia
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cr"></i>
                             Costa Rica
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cu"></i>
                             Cuba
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cv"></i>
                             Cape Verde
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cw"></i>
                             Curacao
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cx"></i>
                             Christmas Island
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cy"></i>
                             Cyprus
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cz"></i>
                             Czech Republic
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-de"></i>
                             Germany
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-dj"></i>
                             Djibouti
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-dk"></i>
                             Denmark
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-dm"></i>
                             Dominica
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-do"></i>
                             Dominican Republic
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-dz"></i>
                             Algeria
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ec"></i>
                             Ecuador
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ee"></i>
                             Estonia
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-eg"></i>
                             Egypt
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-eh"></i>
                             Western Sahara
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-er"></i>
                             Eritrea
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-es"></i>
                             Spain
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-et"></i>
                             Ethiopia
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-fi"></i>
                             Finland
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-fj"></i>
                             Fiji
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-fk"></i>
                             Falkland Islands
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-fm"></i>
                             Micronesia
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-fo"></i>
                             Faroe Islands
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-fr"></i>
                             France
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ga"></i>
                             Gabon
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gb"></i>
                             United Kingdom
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gd"></i>
                             Grenada
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ge"></i>
                             Georgia
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gf"></i>
                             French Guiana
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gg"></i>
                             Guernsey
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gh"></i>
                             Ghana
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gi"></i>
                             Gibraltar
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gl"></i>
                             Greenland
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gm"></i>
                             Gambia
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gn"></i>
                             Guinea
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gp"></i>
                             Guadeloupe
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gq"></i>
                             Equatorial Guinea
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gr"></i>
                             Greece
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gs"></i>
                             South Georgia and the South Sandwich Islands
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gt"></i>
                             Guatemala
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gu"></i>
                             Guam
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gw"></i>
                             Guinea-Bissau
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-gy"></i>
                             Guyana
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-hk"></i>
                             Hong Kong
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-hm"></i>
                             Heard Island and McDonald Islands
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-hn"></i>
                             Honduras
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-hr"></i>
                             Croatia
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ht"></i>
                             Haiti
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-hu"></i>
                             Hungary
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-id"></i>
                             Indonesia
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ie"></i>
                             Ireland
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-il"></i>
                             Israel
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-im"></i>
                             Isle of Man
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-in"></i>
                             India
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-io"></i>
                             British Indian Ocean Territory
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-iq"></i>
                             Iraq
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ir"></i>
                             Iran
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-is"></i>
                             Iceland
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-it"></i>
                             Italy
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-je"></i>
                             Jersey
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-jm"></i>
                             Jamaica
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-jo"></i>
                             Jordan
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-jp"></i>
                             Japan
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ke"></i>
                             Kenya
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-kg"></i>
                             Kyrgyzstan
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-kh"></i>
                             Cambodia
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ki"></i>
                             Kiribati
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-km"></i>
                             Comoros
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-kn"></i>
                             Saint Kitts and Nevis
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-kp"></i>
                             North Korea
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-kr"></i>
                             South Korea
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-kw"></i>
                             Kuwait
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ky"></i>
                             Cayman Islands
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-kz"></i>
                             Kazakhstan
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-la"></i>
                             Laos
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-lb"></i>
                             Lebanon
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-lc"></i>
                             Saint Lucia
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-li"></i>
                             Liechtenstein
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-lk"></i>
                             Sri Lanka
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-lr"></i>
                             Liberia
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ls"></i>
                             Lesotho
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-lt"></i>
                             Lithuania
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-lu"></i>
                             Luxembourg
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-lv"></i>
                             Latvia
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ly"></i>
                             Libya
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ma"></i>
                             Morocco
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-mc"></i>
                             Monaco
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-md"></i>
                             Moldova
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-me"></i>
                             Montenegro
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-mf"></i>
                             Saint Martin
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-mg"></i>
                             Madagascar
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-mh"></i>
                             Marshall Islands
                         </h3>,
 <h3 class="country-name">
 <i class="flag-icon flag-icon-mk"></i>
                             Macedonia
                         </h3>,
 <h3 class="country-name">

In [33]:
for country in country_name:
  print(country.text.strip())

Andorra
United Arab Emirates
Afghanistan
Antigua and Barbuda
Anguilla
Albania
Armenia
Angola
Antarctica
Argentina
American Samoa
Austria
Australia
Aruba
Åland
Azerbaijan
Bosnia and Herzegovina
Barbados
Bangladesh
Belgium
Burkina Faso
Bulgaria
Bahrain
Burundi
Benin
Saint Barthélemy
Bermuda
Brunei
Bolivia
Bonaire
Brazil
Bahamas
Bhutan
Bouvet Island
Botswana
Belarus
Belize
Canada
Cocos [Keeling] Islands
Democratic Republic of the Congo
Central African Republic
Republic of the Congo
Switzerland
Ivory Coast
Cook Islands
Chile
Cameroon
China
Colombia
Costa Rica
Cuba
Cape Verde
Curacao
Christmas Island
Cyprus
Czech Republic
Germany
Djibouti
Denmark
Dominica
Dominican Republic
Algeria
Ecuador
Estonia
Egypt
Western Sahara
Eritrea
Spain
Ethiopia
Finland
Fiji
Falkland Islands
Micronesia
Faroe Islands
France
Gabon
United Kingdom
Grenada
Georgia
French Guiana
Guernsey
Ghana
Gibraltar
Greenland
Gambia
Guinea
Guadeloupe
Equatorial Guinea
Greece
South Georgia and the South Sandwich Islands
Guatemala
Guam
Guinea-Bissau
Guyana
Hong Kong
Heard Island and McDonald Islands
Honduras
Croatia
Haiti
Hungary
Indonesia
Ireland
Israel
Isle of Man
India
British Indian Ocean Territory
Iraq
Iran
Iceland
Italy
Jersey
Jamaica
Jordan
Japan
Kenya
Kyrgyzstan
Cambodia
Kiribati
Comoros
Saint Kitts and Nevis
North Korea
South Korea
Kuwait
Cayman Islands
Kazakhstan
Laos
Lebanon
Saint Lucia
Liechtenstein
Sri Lanka
Liberia
Lesotho
Lithuania
Luxembourg
Latvia
Libya
Morocco
Monaco
Moldova
Montenegro
Saint Martin
Madagascar
Marshall Islands
Macedonia
Mali
Myanmar [Burma]
Mongolia
Macao
Northern Mariana Islands
Martinique
Mauritania
Montserrat
Malta
Mauritius
Maldives
Malawi
Mexico
Malaysia
Mozambique
Namibia
New Caledonia
Niger
Norfolk Island
Nigeria
Nicaragua
Netherlands
Norway
Nepal
Nauru
Niue
New Zealand
Oman
Panama
Peru
French Polynesia
Papua New Guinea
Philippines
Pakistan
Poland
Saint Pierre and Miquelon
Pitcairn Islands
Puerto Rico
Palestine
Portugal
Palau
Paraguay
Qatar
Réunion
Romania
Serbia
Russia
Rwanda
Saudi Arabia
Solomon Islands
Seychelles
Sudan
Sweden
Singapore
Saint Helena
Slovenia
Svalbard and Jan Mayen
Slovakia
Sierra Leone
San Marino
Senegal
Somalia
Suriname
South Sudan
São Tomé and Príncipe
El Salvador
Sint Maarten
Syria
Swaziland
Turks and Caicos Islands
Chad
French Southern Territories
Togo
Thailand
Tajikistan
Tokelau
East Timor
Turkmenistan
Tunisia
Tonga
Turkey
Trinidad and Tobago
Tuvalu
Taiwan
Tanzania
Ukraine
Uganda
U.S. Minor Outlying Islands
United States
Uruguay
Uzbekistan
Vatican City
Saint Vincent and the Grenadines
Venezuela
British Virgin Islands
U.S. Virgin Islands
Vietnam
Vanuatu
Wallis and Futuna
Samoa
Kosovo
Yemen
Mayotte
South Africa
Zambia
Zimbabwe

In [34]:
len(df)

0

In [35]:
for country in country_name:
  length = len(df)
  df.loc[length] = country.text.strip()

In [36]:
len(df)

250

In [37]:
df

                  Country
0                 Andorra
1    United Arab Emirates
2             Afghanistan
3     Antigua and Barbuda
4                Anguilla
..                    ...
245                 Yemen
246               Mayotte
247          South Africa
248                Zambia
249              Zimbabwe

[250 rows x 1 columns]

In [38]:
df.head(10)

                Country
0               Andorra
1  United Arab Emirates
2           Afghanistan
3   Antigua and Barbuda
4              Anguilla
5               Albania
6               Armenia
7                Angola
8            Antarctica
9             Argentina

In [39]:
country_info = soup.find_all('div',class_='country')
country_info

[<div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ad"></i>
                             Andorra
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Andorra la Vella</span><br/>
 <strong>Population:</strong> <span class="country-population">84000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">468.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ae"></i>
                             United Arab Emirates
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Abu Dhabi</span><br/>
 <strong>Population:</strong> <span class="country-population">4975593</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">82880.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-af"></i>
                             Afghanistan
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Kabul</span><br/>
 <strong>Population:</strong> <span class="country-population">29121286</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">647500.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ag"></i>
                             Antigua and Barbuda
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">St. John's</span><br/>
 <strong>Population:</strong> <span class="country-population">86754</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">443.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ai"></i>
                             Anguilla
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">The Valley</span><br/>
 <strong>Population:</strong> <span class="country-population">13254</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">102.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-al"></i>
                             Albania
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Tirana</span><br/>
 <strong>Population:</strong> <span class="country-population">2986952</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">28748.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-am"></i>
                             Armenia
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Yerevan</span><br/>
 <strong>Population:</strong> <span class="country-population">2968000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">29800.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ao"></i>
                             Angola
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Luanda</span><br/>
 <strong>Population:</strong> <span class="country-population">13068161</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1246700.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-aq"></i>
                             Antarctica
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">None</span><br/>
 <strong>Population:</strong> <span class="country-population">0</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1.4E7</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ar"></i>
                             Argentina
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Buenos Aires</span><br/>
 <strong>Population:</strong> <span class="country-population">41343201</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">2766890.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-as"></i>
                             American Samoa
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Pago Pago</span><br/>
 <strong>Population:</strong> <span class="country-population">57881</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">199.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-at"></i>
                             Austria
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Vienna</span><br/>
 <strong>Population:</strong> <span class="country-population">8205000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">83858.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-au"></i>
                             Australia
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Canberra</span><br/>
 <strong>Population:</strong> <span class="country-population">21515754</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">7686850.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-aw"></i>
                             Aruba
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Oranjestad</span><br/>
 <strong>Population:</strong> <span class="country-population">71566</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">193.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ax"></i>
                             Åland
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Mariehamn</span><br/>
 <strong>Population:</strong> <span class="country-population">26711</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1580.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-az"></i>
                             Azerbaijan
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Baku</span><br/>
 <strong>Population:</strong> <span class="country-population">8303512</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">86600.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ba"></i>
                             Bosnia and Herzegovina
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Sarajevo</span><br/>
 <strong>Population:</strong> <span class="country-population">4590000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">51129.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bb"></i>
                             Barbados
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Bridgetown</span><br/>
 <strong>Population:</strong> <span class="country-population">285653</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">431.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bd"></i>
                             Bangladesh
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Dhaka</span><br/>
 <strong>Population:</strong> <span class="country-population">156118464</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">144000.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-be"></i>
                             Belgium
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Brussels</span><br/>
 <strong>Population:</strong> <span class="country-population">10403000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">30510.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bf"></i>
                             Burkina Faso
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Ouagadougou</span><br/>
 <strong>Population:</strong> <span class="country-population">16241811</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">274200.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bg"></i>
                             Bulgaria
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Sofia</span><br/>
 <strong>Population:</strong> <span class="country-population">7148785</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">110910.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bh"></i>
                             Bahrain
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Manama</span><br/>
 <strong>Population:</strong> <span class="country-population">738004</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">665.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bi"></i>
                             Burundi
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Bujumbura</span><br/>
 <strong>Population:</strong> <span class="country-population">9863117</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">27830.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bj"></i>
                             Benin
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Porto-Novo</span><br/>
 <strong>Population:</strong> <span class="country-population">9056010</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">112620.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bl"></i>
                             Saint Barthélemy
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Gustavia</span><br/>
 <strong>Population:</strong> <span class="country-population">8450</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">21.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bm"></i>
                             Bermuda
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Hamilton</span><br/>
 <strong>Population:</strong> <span class="country-population">65365</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">53.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bn"></i>
                             Brunei
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Bandar Seri Begawan</span><br/>
 <strong>Population:</strong> <span class="country-population">395027</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">5770.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bo"></i>
                             Bolivia
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Sucre</span><br/>
 <strong>Population:</strong> <span class="country-population">9947418</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1098580.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bq"></i>
                             Bonaire
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Kralendijk</span><br/>
 <strong>Population:</strong> <span class="country-population">18012</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">328.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-br"></i>
                             Brazil
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Brasília</span><br/>
 <strong>Population:</strong> <span class="country-population">201103330</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">8511965.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bs"></i>
                             Bahamas
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Nassau</span><br/>
 <strong>Population:</strong> <span class="country-population">301790</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">13940.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bt"></i>
                             Bhutan
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Thimphu</span><br/>
 <strong>Population:</strong> <span class="country-population">699847</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">47000.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bv"></i>
                             Bouvet Island
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">None</span><br/>
 <strong>Population:</strong> <span class="country-population">0</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">49.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bw"></i>
                             Botswana
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Gaborone</span><br/>
 <strong>Population:</strong> <span class="country-population">2029307</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">600370.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-by"></i>
                             Belarus
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Minsk</span><br/>
 <strong>Population:</strong> <span class="country-population">9685000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">207600.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bz"></i>
                             Belize
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Belmopan</span><br/>
 <strong>Population:</strong> <span class="country-population">314522</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">22966.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ca"></i>
                             Canada
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Ottawa</span><br/>
 <strong>Population:</strong> <span class="country-population">33679000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">9984670.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cc"></i>
                             Cocos [Keeling] Islands
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">West Island</span><br/>
 <strong>Population:</strong> <span class="country-population">628</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">14.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cd"></i>
                             Democratic Republic of the Congo
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Kinshasa</span><br/>
 <strong>Population:</strong> <span class="country-population">70916439</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">2345410.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cf"></i>
                             Central African Republic
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Bangui</span><br/>
 <strong>Population:</strong> <span class="country-population">4844927</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">622984.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cg"></i>
                             Republic of the Congo
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Brazzaville</span><br/>
 <strong>Population:</strong> <span class="country-population">3039126</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">342000.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ch"></i>
                             Switzerland
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Bern</span><br/>
 <strong>Population:</strong> <span class="country-population">7581000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">41290.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">